import { Product, ProductVariant, Size } from '@/types/product';

const sizes: Size[] = ['S', 'M', 'L', 'XL', 'XXL'];
const defaultVariants: ProductVariant[] = sizes.map(size => ({ size, inStock: true, stock: 10 }));

export const products: Product[] = [
  {
    id: 'prod_1',
    slug: 'dynasty-og-hoodie',
    name: 'Dynasty OG Hoodie',
    description: 'Heavyweight premium cotton hoodie with our signature box fit and front puff print.',
    price: 85000,
    category: 'hoodies',
    images: ['/products/dynasty-og-hoodie-front.jpg', '/products/dynasty-og-hoodie-back.jpg'],
    variants: defaultVariants,
    badge: 'new-drop',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    slug: 'neon-abyss-hoodie',
    name: 'Neon Abyss Hoodie',
    description: 'Oversized hoodie with cyber-punk inspired graphics and distressed detailing.',
    price: 82000,
    category: 'hoodies',
    images: ['/products/neon-abyss-hoodie-front.jpg', '/products/neon-abyss-hoodie-back.jpg'],
    variants: defaultVariants,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    slug: 'chrome-skull-hoodie',
    name: 'Chrome Skull Hoodie',
    description: 'Fleece-lined hoodie featuring a metallic chrome skull print on the back.',
    price: 79000,
    category: 'hoodies',
    images: ['/products/chrome-skull-hoodie-front.jpg', '/products/chrome-skull-hoodie-back.jpg'],
    variants: defaultVariants,
    badge: 'exclusive',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    slug: 'built-different-tee',
    name: 'Built Different Tee',
    description: 'Heavyweight 250gsm oversize tee featuring our brand slogan.',
    price: 35000,
    compareAtPrice: 42000,
    category: 'tees',
    images: ['/products/built-different-tee-front.jpg', '/products/built-different-tee-back.jpg'],
    variants: defaultVariants,
    badge: 'new-drop',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    slug: 'monogram-oversize-tee',
    name: 'Monogram Oversize Tee',
    description: 'Minimalist oversize tee with DYG monogram embroidery.',
    price: 32000,
    category: 'tees',
    images: ['/products/monogram-oversize-tee-front.jpg', '/products/monogram-oversize-tee-back.jpg'],
    variants: defaultVariants,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    slug: 'phantom-logo-tee',
    name: 'Phantom Logo Tee',
    description: 'Washed out vintage feel tee with a faded phantom logo print.',
    price: 33000,
    category: 'tees',
    images: ['/products/phantom-logo-tee-front.jpg', '/products/phantom-logo-tee-back.jpg'],
    variants: defaultVariants,
    badge: 'restock',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_7',
    slug: 'cargo-dynasty-black',
    name: 'Cargo Dynasty Black',
    description: 'Wide leg tactical cargo pants with adjustable hem toggles and multiple 3D pockets.',
    price: 75000,
    category: 'pants',
    images: ['/products/cargo-dynasty-black-front.jpg', '/products/cargo-dynasty-black-back.jpg'],
    variants: defaultVariants,
    badge: 'limited',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_8',
    slug: 'parachute-pants-olive',
    name: 'Parachute Pants Olive',
    description: 'Ultra-lightweight parachute pants for maximum mobility and flow.',
    price: 68000,
    category: 'pants',
    images: ['/products/parachute-pants-olive-front.jpg', '/products/parachute-pants-olive-back.jpg'],
    variants: defaultVariants,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_9',
    slug: 'dynasty-beanie',
    name: 'Dynasty Beanie',
    description: 'Chunky ribbed knit beanie with woven brand patch.',
    price: 25000,
    category: 'accessories',
    images: ['/products/dynasty-beanie-front.jpg', '/products/dynasty-beanie-back.jpg'],
    variants: defaultVariants,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_10',
    slug: 'crossbody-bag',
    name: 'Crossbody Bag',
    description: 'Compact tactical crossbody bag with matte black hardware and branded strap.',
    price: 45000,
    category: 'accessories',
    images: ['/products/crossbody-bag-front.jpg', '/products/crossbody-bag-back.jpg'],
    variants: defaultVariants,
    badge: 'new-drop',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_11',
    slug: 'chain-link-necklace',
    name: 'Chain Link Necklace',
    description: 'Heavy duty stainless steel chain with custom monogram pendant.',
    price: 28000,
    category: 'accessories',
    images: ['/products/chain-link-necklace-front.jpg', '/products/chain-link-necklace-back.jpg'],
    variants: defaultVariants,
    badge: 'sold-out',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_12',
    slug: 'void-heavy-sweatpants',
    name: 'Void Heavy Sweatpants',
    description: 'Thick fleece sweatpants with elastic cuffs and subtle tonal branding.',
    price: 58000,
    category: 'pants',
    images: ['/products/void-heavy-sweatpants-front.jpg', '/products/void-heavy-sweatpants-back.jpg'],
    variants: defaultVariants,
    createdAt: new Date().toISOString(),
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products;
  return products.filter(p => p.category === category);
}
